# Generated by Django 4.2.11 on 2024-04-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('text_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.textfiles')),
            ],
        ),
    ]
