# Generated by Django 4.2.11 on 2024-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctortext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortext',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text/'),
        ),
    ]
