# Generated by Django 4.2.11 on 2024-04-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_doctortext_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phno',
            field=models.CharField(default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='doctortext',
            name='doctor',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
    ]
