# Generated by Django 4.2.11 on 2024-04-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_doctorinfoextend_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='do_id',
            field=models.IntegerField(default=1),
        ),
    ]
